package com.commodityshareplatform.subject.dao;

import com.commodityshareplatform.subject.bean.Admin;
import com.commodityshareplatform.subject.bean.AdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    long countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    Admin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_admin
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    int updateByPrimaryKey(Admin record);
}