package com.commodityshareplatform.subject.bean;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_admin.ADMIN_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_admin.ADMIN_PASSWORD
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String adminPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_admin.ADMIN_NAME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String adminName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_admin.ADMIN_ID
     *
     * @return the value of t_sys_admin.ADMIN_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_admin.ADMIN_ID
     *
     * @param adminId the value for t_sys_admin.ADMIN_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_admin.ADMIN_PASSWORD
     *
     * @return the value of t_sys_admin.ADMIN_PASSWORD
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_admin.ADMIN_PASSWORD
     *
     * @param adminPassword the value for t_sys_admin.ADMIN_PASSWORD
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_admin.ADMIN_NAME
     *
     * @return the value of t_sys_admin.ADMIN_NAME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_admin.ADMIN_NAME
     *
     * @param adminName the value for t_sys_admin.ADMIN_NAME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }
}