package com.commodityshareplatform.subject.bean;

import java.util.Date;

public class Commodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_NAME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String commodityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_STATUS
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer commodityStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_NUM
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer commodityNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_USER_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer commodityUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_IMG_SRC
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String commodityImgSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_TAG
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String commodityTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_QUALITY
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String commodityQuality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_CREATE_DATE
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Date commodityCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.IS_ VALID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.COMMODITY_DETAILS
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String commodityDetails;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_ID
     *
     * @return the value of t_commodity.COMMODITY_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_ID
     *
     * @param commodityId the value for t_commodity.COMMODITY_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_NAME
     *
     * @return the value of t_commodity.COMMODITY_NAME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_NAME
     *
     * @param commodityName the value for t_commodity.COMMODITY_NAME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_STATUS
     *
     * @return the value of t_commodity.COMMODITY_STATUS
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getCommodityStatus() {
        return commodityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_STATUS
     *
     * @param commodityStatus the value for t_commodity.COMMODITY_STATUS
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityStatus(Integer commodityStatus) {
        this.commodityStatus = commodityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_NUM
     *
     * @return the value of t_commodity.COMMODITY_NUM
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getCommodityNum() {
        return commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_NUM
     *
     * @param commodityNum the value for t_commodity.COMMODITY_NUM
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityNum(Integer commodityNum) {
        this.commodityNum = commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_USER_ID
     *
     * @return the value of t_commodity.COMMODITY_USER_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getCommodityUserId() {
        return commodityUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_USER_ID
     *
     * @param commodityUserId the value for t_commodity.COMMODITY_USER_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityUserId(Integer commodityUserId) {
        this.commodityUserId = commodityUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_IMG_SRC
     *
     * @return the value of t_commodity.COMMODITY_IMG_SRC
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getCommodityImgSrc() {
        return commodityImgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_IMG_SRC
     *
     * @param commodityImgSrc the value for t_commodity.COMMODITY_IMG_SRC
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityImgSrc(String commodityImgSrc) {
        this.commodityImgSrc = commodityImgSrc == null ? null : commodityImgSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_TAG
     *
     * @return the value of t_commodity.COMMODITY_TAG
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getCommodityTag() {
        return commodityTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_TAG
     *
     * @param commodityTag the value for t_commodity.COMMODITY_TAG
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityTag(String commodityTag) {
        this.commodityTag = commodityTag == null ? null : commodityTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_QUALITY
     *
     * @return the value of t_commodity.COMMODITY_QUALITY
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getCommodityQuality() {
        return commodityQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_QUALITY
     *
     * @param commodityQuality the value for t_commodity.COMMODITY_QUALITY
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityQuality(String commodityQuality) {
        this.commodityQuality = commodityQuality == null ? null : commodityQuality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_CREATE_DATE
     *
     * @return the value of t_commodity.COMMODITY_CREATE_DATE
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Date getCommodityCreateDate() {
        return commodityCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_CREATE_DATE
     *
     * @param commodityCreateDate the value for t_commodity.COMMODITY_CREATE_DATE
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityCreateDate(Date commodityCreateDate) {
        this.commodityCreateDate = commodityCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.IS_ VALID
     *
     * @return the value of t_commodity.IS_ VALID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.IS_ VALID
     *
     * @param isValid the value for t_commodity.IS_ VALID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.COMMODITY_DETAILS
     *
     * @return the value of t_commodity.COMMODITY_DETAILS
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getCommodityDetails() {
        return commodityDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.COMMODITY_DETAILS
     *
     * @param commodityDetails the value for t_commodity.COMMODITY_DETAILS
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setCommodityDetails(String commodityDetails) {
        this.commodityDetails = commodityDetails == null ? null : commodityDetails.trim();
    }
}