package com.commodityshareplatform.subject.bean;

import java.util.Date;

public class Order extends OrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_NAME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String orderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_CODE
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_STATUS
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_CREATE_DATE
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Date orderCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_ADDR
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String orderAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_ARRIVE_ADDR
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private String orderArriveAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_BEGIN_RENT_TIME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Date orderBeginRentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_END_RENT_TIME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Date orderEndRentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_BACK_TIME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer orderBackTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.IS_ VALID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_NAME
     *
     * @return the value of t_order.ORDER_NAME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_NAME
     *
     * @param orderName the value for t_order.ORDER_NAME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName == null ? null : orderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_CODE
     *
     * @return the value of t_order.ORDER_CODE
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_CODE
     *
     * @param orderCode the value for t_order.ORDER_CODE
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_STATUS
     *
     * @return the value of t_order.ORDER_STATUS
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_STATUS
     *
     * @param orderStatus the value for t_order.ORDER_STATUS
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_CREATE_DATE
     *
     * @return the value of t_order.ORDER_CREATE_DATE
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Date getOrderCreateDate() {
        return orderCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_CREATE_DATE
     *
     * @param orderCreateDate the value for t_order.ORDER_CREATE_DATE
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderCreateDate(Date orderCreateDate) {
        this.orderCreateDate = orderCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_ADDR
     *
     * @return the value of t_order.ORDER_ADDR
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getOrderAddr() {
        return orderAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_ADDR
     *
     * @param orderAddr the value for t_order.ORDER_ADDR
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderAddr(String orderAddr) {
        this.orderAddr = orderAddr == null ? null : orderAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_ARRIVE_ADDR
     *
     * @return the value of t_order.ORDER_ARRIVE_ADDR
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getOrderArriveAddr() {
        return orderArriveAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_ARRIVE_ADDR
     *
     * @param orderArriveAddr the value for t_order.ORDER_ARRIVE_ADDR
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderArriveAddr(String orderArriveAddr) {
        this.orderArriveAddr = orderArriveAddr == null ? null : orderArriveAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_BEGIN_RENT_TIME
     *
     * @return the value of t_order.ORDER_BEGIN_RENT_TIME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Date getOrderBeginRentTime() {
        return orderBeginRentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_BEGIN_RENT_TIME
     *
     * @param orderBeginRentTime the value for t_order.ORDER_BEGIN_RENT_TIME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderBeginRentTime(Date orderBeginRentTime) {
        this.orderBeginRentTime = orderBeginRentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_END_RENT_TIME
     *
     * @return the value of t_order.ORDER_END_RENT_TIME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Date getOrderEndRentTime() {
        return orderEndRentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_END_RENT_TIME
     *
     * @param orderEndRentTime the value for t_order.ORDER_END_RENT_TIME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderEndRentTime(Date orderEndRentTime) {
        this.orderEndRentTime = orderEndRentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_BACK_TIME
     *
     * @return the value of t_order.ORDER_BACK_TIME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getOrderBackTime() {
        return orderBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_BACK_TIME
     *
     * @param orderBackTime the value for t_order.ORDER_BACK_TIME
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderBackTime(Integer orderBackTime) {
        this.orderBackTime = orderBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.IS_ VALID
     *
     * @return the value of t_order.IS_ VALID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.IS_ VALID
     *
     * @param isValid the value for t_order.IS_ VALID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}